name: Build image

permissions:
  contents: read

on:
  workflow_call:
    secrets:
      bot_key:
      bot_id:
    inputs:
      os_family:
        type: string
        default: linux
      host_platform:
        type: string
        default: ubuntu-22.04
      gcr_name:
        type: string
        default: envoy-build

      go_version:
        type: string
        default: '1.16'


jobs:
  regenerate_toolchain:
    runs-on: ${{ inputs.host_platform }}
    name: Regenerate toolchain
    steps:
    - id: appauth
      uses: envoyproxy/toolshed/gh-actions/appauth@actions-v0.0.17
      with:
        key: ${{ secrets.bot_key }}
        app_id: ${{ secrets.bot_id }}
    - name: 'Checkout Repository'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ steps.appauth.outputs.token }}
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go_version }}
        cache: false
    - run: |
        toolchains/regenerate.sh
      shell: bash
      env:
        COMMIT_TOOLCHAINS: true
        GCR_IMAGE_NAME: ${{ inputs.gcr_name }}
        OS_FAMILY: ${{ inputs.os_family }}
        SOURCE_BRANCH: ${{ github.ref }}
        # TODO(phlax): remove when 1.26 goes EOL
        CONTAINER_PREFIX: "${{ inputs.distro == 'ubuntu' && 'cmake-' || '' }}"
